### PR TITLE
Involuntary peer reviewing

### PR DESCRIPTION
**Pull request by Phatcat**
You guys are kind of forcing my hand here, if you'd just PR your own work I wouldn't have to do this; and believe me, I will keep on doing this if this is how you guys want to play this.

https://github.com/NostalriusTBC/Core
https://github.com/kraminpouds/mangos-classic/tree/develop
https://github.com/zwisus/ElunaMangosClassic
https://github.com/51kfa/mangos-classic
https://github.com/anathemareborn/core
https://github.com/NostalriusReborn/Core
https://github.com/keyshuwen

---
This change is [Reviewable](https://reviewable.io/reviews/cmangos/mangos-classic/139)

### CODE REVIEW

**Comment by sidsukana** [comment]
I'm not against :)

**Comment by sidsukana** [comment]
Some of these fixations require careful study by community

**Comment by cyberium** [comment]
Well iam not against too, but each commit should be reviewed one by one and removed from this pr. So you just add a good list of work for you :p (and all that want to help ofc)

**Comment by Phatcat** [comment]
Yes, each commit has to be studied individually, this is just the collection, also it's a neat way to make sure they all can build.

**Comment by Laizerox** [comment]
I would be really careful with 61dacf0e86f6f4024c5d94e24569bcb63d9c97ab last time I tested it caused some WMO to ignore LoS Completely (For example dungeon near goldshire)

**Comment by killerwife** [comment]
This is too miscellaneous to actually review. A lot of the stuff thats especially related to spells might be downright dangerous despite the authors best intentions. I think this will need to be PRed one by one. Pet stuff works this way but spell stuff doesnt.

**Comment by sidsukana** [comment]
I can split commit https://github.com/cmangos/mangos-classic/pull/139/commits/52804cd8f813206149567d475670e70a9b187e96 into several parts, which can be added separately. 

I am writing this change and I can say that it works correctly (for 2 years it works on the valkyrie-wow :))

**Comment by Phatcat** [comment]
> each commit should be reviewed one by one and removed from this pr.

-

> Yes, each commit has to be studied individually, this is just the collection, also it's a neat way to make sure they all can build.

**Comment by Phatcat** [comment]
@Laizerox I pulled both of them from this PR; no reason to hang on to non proper code; we can write our own improper code.

**Comment by Phatcat** [comment]
Oh noes...

**Comment by Phatcat** [comment]
Okay, too many commits to keep track of, going to split these.

**Comment by Muehe** [comment]
https://github.com/cmangos/mangos-classic/pull/139/commits/a57617a8a1dcbcbdf2b746f5717868a404d6271b (修复盗贼天赋 强化疾跑 = Repair thieves talent Improved Sprint) already has open PR: https://github.com/cmangos/mangos-classic/pull/31

There seem to be some concerns about it being the correct way to solve this.

**Comment by killerwife** [comment]
Added https://git.io/voZdv its something that is in this PR and I had it on Vengeance. Its tested and hence can be removed from this.

**Comment by Phatcat** [comment]
https://github.com/cmangos/mangos-classic/pull/139/commits/a57617a8a1dcbcbdf2b746f5717868a404d6271b is getting removed.

**Comment by Muehe** [comment]
https://github.com/cmangos/mangos-classic/pull/139/commits/a502929d6a0387e56bbe098c37092215c3a83601 (Feline Swiftness) related:

https://github.com/cmangos/issues/issues/434
https://github.com/cmangos/mangos-classic/pull/115
https://github.com/cmangos/issues/issues/724

**Comment by Muehe** [comment]
https://github.com/cmangos/mangos-classic/pull/139/commits/fadc77e72aa2b21d8237348816ecef770f3aeaab is fixed according to https://github.com/cmangos/issues/issues/906

Also see:
https://github.com/cmangos/issues/issues/489
https://github.com/cmangos/issues/issues/895

**Comment by Phatcat** [comment]
Thank you my good sir.

**Comment by Muehe** [comment]
https://github.com/cmangos/mangos-classic/pull/139/commits/6d09a830101e314716846238b81100a66c2867f9 and https://github.com/cmangos/mangos-classic/pull/139/commits/096f6889e63ccea0a46e9abef187f26422796462 have a merge conflict in Unit::SetFeared

**Comment by Muehe** [comment]
https://github.com/cmangos/mangos-classic/pull/139/commits/210c639a80f4df336cc77ac813921cee2adf3c4a (Dont dispel aura on damage caused by aura itself) is related to:

https://github.com/cmangos/issues/issues/890
https://github.com/cmangos/mangos-classic/pull/130

**Comment by Muehe** [comment]
https://github.com/cmangos/mangos-classic/pull/139/commits/15570494a5a9b44ca95cb9fccd5fc7325cfc5a79 and https://github.com/cmangos/mangos-classic/pull/139/commits/0bf5213ed451a48a47cc4b68ceb61c07ad2a6d6c seem to approach the same issue differently.

Related to https://github.com/cmangos/issues/issues/281 and issues named therein.

**Comment by Muehe** [comment]
Commits relating to config settings:

https://github.com/cmangos/mangos-classic/pull/139/commits/338a6c2b7cdb6a500e24c3d7ef9f42243f1f8724
https://github.com/cmangos/mangos-classic/pull/139/commits/4634f600d01942349b68bf4dd403bd11fcc74632
https://github.com/cmangos/mangos-classic/pull/139/commits/00959dd2131e7cefbd1bed3441ae6248606c59a4 (not sure on this one)

**Comment by Phatcat** [comment]
> 6d09a83 and 096f688 have a merge conflict in Unit::SetFeared
 - No, you just have to reverse the order in which you pull them in...

**Comment by Muehe** [comment]
Not merge conflict as in I actually pulled it. Just thought that if statement would get added twice. Wouldn't it? Muehe::SetConfused(); :smile: I'm not that git-savvy...

**Comment by Phatcat** [comment]
Oh, like that. No, all of this is not supposed to go together, no. This is just one giant collection of stuff, and some commits solve the same shit in different ways as you say, as this comes from about 4 different private servers and a few single developers not pr'ing.

Currently splitting it up in different branches.

**Comment by Phatcat** [comment]
alive

**Comment by Phatcat** [comment]
> Edit: 21a42870cd9ae479776a1ea8dfbe57041e911224 I don't like this approach, I've been looking into spell flags and I've noticed that spells that use rage & energy and may award combo points have special attributes that will refund energy / rage (formula of how much refunded is still pending)

you mean something more like this https://github.com/cmangos/mangos-classic/pull/139/commits/038fda131b5bbfa6db3cb15a334acd0844c0e80a ?

**Comment by robinsch** [comment]
I mean not really, those should be fine to merge. But there are other commits over at NostTBC that are worth checking out (I'm not going to highlight them, but if you have any questions about the changes just ask).

https://github.com/cmangos/mangos-classic/pull/139/commits/9d4efb74a42bc5319689c43d8a4a27db496d996f
https://github.com/cmangos/mangos-classic/pull/139/commits/4d2b551578db9a7dc2152e69739b591878727f76

**Comment by Phatcat** [comment]
I don't quite understand, you say they are all fine to merge, but you then only go on to list 2 of the 4 commits by you on this PR? - also I'm not just gonna merge them, they're gonna go through a PR process.

Actually I been over all the commits of NostTBC and I did not find anything besides these commits of yours here (and those already merged with cmangos) much interesting. I may have overlooked stuff. there was your Grounding totem commit but it seemed you weren't yourself too happy with that one.

**Comment by robinsch** [comment]
Nonono, PR whatever you want. I super fine with that, that's why I went open source with TBCPvP. 
About https://github.com/cmangos/mangos-classic/pull/139/commits/9700cfb33bc68743bc647f8a0a045ba0f7c0ba62 this should be handled somewhere else.

**Comment by Phatcat** [comment]
Closing this PR, something really messed up when I tried to clean it up tonight so I'm not gonna bother with it as a collection anymore. Doesn't mean I have just thrown all of these out, still gonna come look these through whenever I get some spare time, which is not much lately..

**Pull request closed without merging**
