### PR TITLE
Update scriptdev part of README

### PR DESCRIPTION
**Pull request by Phatcat**
@xfurry

---
This change is [Reviewable](https://reviewable.io/reviews/cmangos/mangos-classic/163)

### CODE REVIEW

**Comment by dagochen** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cmangos/mangos-classic/163)*

**Comment by Phatcat** [comment]
:heart: Finally, someone to actually use reviewable :yum:

**Comment by dagochen** [comment]
Sorry if I jumped in here ;) Wanted to try it out and this seemed like a less important commit so....^^

**Comment by xfurry** [comment]
Why are you asking me to review this PR?
Just go ahead and merge it. You already know that it's fine.

**Comment by Phatcat** [comment]
Not asking you to review, just showing you before I merge it; I am not 100% familiar with scriptdev2, I didn't know if you guys had a external site somewhere you wanted added or anything, sorry.

I'll just go ahead and merge it then =)

**Comment by xfurry** [comment]
We had an external site, but now it's merged into the current one (content as well)

http://cmangos.net/forum-32.html

**Comment by Phatcat** [comment]
That was the impression I had gotten as well, so I indeed did link the subforum.

**Comment by Phatcat** [comment]
Merged.

**Pull request closed without merging**
