### PR TITLE
Remove external Mersenne Twister

### PR DESCRIPTION
**Pull request by sidsukana**
Replace to internal boost::random::mersenne_twister

### CODE REVIEW

**Comment by killerwife** [comment]
Dont even use boost, use STD mersenne twister.

**Comment by Phatcat** [comment]
Why?

We are dependant on boost, no? - so why not just embrace that?

Is it worth the 450ish lines to have our own solution when we can just pull one from boost?

**Comment by killerwife** [comment]
Because boost can be removed in the future, with newest c++ standards stuff. We are using STD everywhere we can, c++11 rewrites were the reason for that, so in my opinion STD>Boost>other stuff. I used #include <random> for all I needed for doing very heavy simulations, hence I can vouch for its functionality.

TL;DR in the future we might get rid of boost, but we will never get rid of STD

**Comment by sidsukana** [comment]
Hmm, I had a different opinion on this)
Boost optimized library that promotes new standards for C++. It is more updated and optimized. When will be the next new STD version?

**Comment by sidsukana** [comment]
I would like to know what the code development policies adhere to Mangos?

**Comment by killerwife** [comment]
Well, lets summon the higher ups @cyberium @namreeb since they are the ones working with this stuff. In the end both generators are most likely the same. I just prefer to use STD when I can.

**Comment by sidsukana** [comment]
@killerwife i agree) i create topic on forum http://cmangos.net/thread-7528.html

**Comment by sidsukana** [comment]
Rework for std::mt19937
I have my doubts about the seed. I used seed_seq of 2 values: time() and clock(). Is this enough to be?

**Comment by killerwife** [comment]
I used std::random_device, but this also has its drawbacks. As it is implementation dependant, on MSVC it gives a higher precision seed than clock(), but may very well be different on GCC. Generally you want nanotime, time and clock are seconds afaik.

**Comment by sidsukana** [comment]
@killerwife 
I read about the advantages and disadvantages random_device and decided to stay until the district is that used Mangos (but without the hash values itih) instead I decided to use seed_seq.
Alternatively, you can add additional source - random_device

**Comment by Phatcat** [comment]
So what is the verdict on this one? Is it good to merge or how are we? @sidsukana @killerwife @namreeb @evil-at-wow ?

**Comment by Phatcat** [comment]
@cyberium @VladimirMangos @xfurry last callout before merging this.

**Pull request closed without merging**
