### PR TITLE
ExtractResources.sh CPU conditional statement fix

### PR DESCRIPTION
**Pull request by ekg98**
Fixed CPU select conditional statement.

### CODE REVIEW

**Comment by killerwife** [comment]
I am gonna ask what issue this fixes. I know very little about shell script syntax.

**Comment by ekg98** [comment]
For some reason anytime I execute the script it does not like the previous conditional.  It gives errors.  Looks like somebody for got and was programming c at the time or something.

./ExtractResources.sh: 94 ./ExtractResources.sh Syntax error: word unexpecting (expecting ")")

I am reading the 9th edition of the linux bible.  Its saying -eq and = are the same in some regards.  I could have just used one equals.

[var1 = var2]
[var1 -eq var2]

This book is saying that both these statements are equal.  I have only tried the second one.

**Comment by cala** [comment]
Kind of busy lately but I have not forgotten this PR that was successfully tested with mac OS. I should be able to test it with Windows bash-shell on Monday.

**Comment by cala** [comment]
Merged, thank you!

**Pull request merged**
