### PR TITLE
fix uninitialized pointer

### PR DESCRIPTION
**Pull request by Tobschinski**
https://github.com/cmangos/issues/issues/1613

### CODE REVIEW

**Comment by cala** [comment]
Good catch. I do not have this issue on mac OS, so I can't test it but you are more than probably right.

**Comment by Tobschinski** [comment]
when did I ever disappoint you

**Comment by cala** [comment]
> when did I ever disappoint you

I cannot remember when, but elephants are famous for their memory, not turtles. So that does not prove a thing. Maybe I forgot when in the past century of my long turtle life.

**Comment by cala** [comment]
Thank you! :+1: :heart:

**Pull request merged**
