### PR TITLE
Use real unit movemenflags when building movement

### PR DESCRIPTION
**Pull request by Laizerox**

### CODE REVIEW

**Comment by ryancheung** [comment]
This would cause client crash if you teleport to felwood!

**Comment by Laizerox** [comment]
Yes I'm aware that it currently crashes client. It's because of splines (most likely) and I'm looking into it with @Tobschinski

**Comment by Muehe** [comment]
May I humbly ask why you closed this PR? Was related to cmangos/issues#729, right?

**Comment by Laizerox** [comment]
Fixed in cmangos/mangos-classic@1def0a8 and cmangos/mangos-classic@0d95ddc

**Pull request closed without merging**
