### PR TITLE
Fix spell instant kill log

### PR DESCRIPTION
**Pull request by mityada**
SMSG_SPELLINSTAKILLLOG now has the correct structure.

See #195.

### CODE REVIEW

**Comment by Phatcat** [comment]
This is for classic only? the current structure for tbc and wrath is correct already?

**Comment by mityada** [comment]
Yep.

**Comment by Phatcat** [comment]
Alright, so what difference to master does this one do exactly? Not entirely sure how to test this one out to see the effects of it.

**Comment by Warlockbugs** [comment]
Perhaps, you can use Warlock's Demonic Sacrifice on pet. This is an instakill effect.

**Comment by Phatcat** [comment]
you're right, didn't think of that one at all.

on master it simply goes

"you have slain <pet name>!"

On this patch it says 

"<pet name> is killed by <spell name>"
"you have slain <pet name>!"

:+1:

Merged.

**Pull request closed without merging**
