### PR TITLE
Implemented school immunity for creature from database

### PR DESCRIPTION
**Pull request by sidsukana**
There are many creatures that are immune to a particular school of magic (such as bosses) patch makes it possible to establish immunity for school in the database

### CODE REVIEW

**Comment by Phatcat** [comment]
This looks good. I see no reason not to implement this.
Just squash your commit into a single one and then maybe @cala or @xfurry could give their 2 cents on this?

**Comment by cyberium** [comment]
Maybe @killerwife can also be a good reviewer on this :) Thank @Phatcat for your precious comment.

**Comment by cala** [comment]
Sorry, I have urgent personnal matters to attend to the last few weeks. I agree we need such a mechanics: there are lots of NPCs with immunity to a specific school and only a handful of them can be done by spell. So definitely, we need this. I did not have the time to test this PR however so I can't if it works/is proper/as side effects but usuallybI trust @sidsukana work.

**Comment by killerwife** [comment]
I will look at this immediately when I have time :)

**Comment by cala** [comment]
Not tested, but looks good to me.

**Comment by xfurry** [comment]
> Not tested, but looks good to me.

Same answer from me.
However I strongly advise that we should test this, before merging (although I'm pretty sure it will be fine)

**Comment by cala** [comment]
> However I strongly advise that we should test this

I agree. I'll try to give it a shot this WE.

**Comment by cyberium** [comment]
Reminder

**Comment by cala** [comment]
Do not be that impatient. :tongue: 
I was precisely compiling it when you wrote your message. Tested right now with a few single immunities and some combinations, it looks very good to me (immunity).

I see only three improvements so far:
- if I set the physical damage school immunity for a NPC, it will be immune to all spells with physical damage, as intended. However, it will take normal melee/range damage (including bow, gun or wand). I think a check for immunities should also be added in the melee/range damage calculation
- This is also true for NPCs immune to a specific school (like nature) if they are attacked by a nature wand: they do take damage while they should not
- if the NPC is out of combat and attacked with a spell it is immune to, it will not react. This is wrong: it should attack the caster.

Overhaul, as it is, the patch is already a much welcome improvement.

**Comment by sidsukana** [comment]
I worked on it but there is a problem
Wand's school damage received from `item_template.dam_type` and overrides in Spell creating. But basic spell immune methods receive spell school from SpellEntry. Need global research for this case.

**Comment by killerwife** [comment]
Those should be the same I think?

**Comment by sidsukana** [comment]
I think yes. The simplest solution is to transfer in real SpellHitResult mask. However, we do not solve the problem of what GetSpellShoolMask returns no real mask for similar cases

**Comment by cala** [comment]
Here is my proposal:
- the current PR adds the feature it is intended to fix
- it introduces no regression
- the issues I mentioned are not directly related to that PR but could use it to be fixed later

So, I suggest to merge that PR and to open an issue in our tracker related to the points mentioned above. What do you think?

**Comment by cyberium** [comment]
@sidsukana or @cala do you think this PR is applicable to other core as well and as it is?

**Comment by xfurry** [comment]
@cyberium I think yes.
I don't see any reason why this won't apply to the newer versions.

**Comment by sidsukana** [comment]
I don't know how add new commits to this topic)))
https://github.com/sidsukana/mangos-classic/commit/5f3f2a2132004e5e0a80ea36737827c7fe46b3ae
this version with physical damage school immunity, includes wabd problem

**Comment by cala** [comment]
> @sidsukana or @cala do you think this PR is applicable to other core as well and as it is?

Yes it is applicable to all cores.
The only thing to take care of is the structure of the SQL storage which is different from a core to another (not the same count of entries).

**Comment by killerwife** [comment]
I will take care of it on TBC-DB end (guess who i will annoy). I am sure @Grz3s will not have an issue with implementing this.

**Comment by Phatcat** [comment]
@sidsukana
Open your master branch in whatever command line tool you use for git (not common to do prs from master, but it doesn't really matter) - if you do not use a command line tool, you need to start including it; on your master branch within the github client, press the options wheel in the right upper corner;
press **`open in git shell`** - make sure that you are on the master branch.

Now you are ready to enter in git commands. The one we'll be using for this is **`git rebase -i head~n`** where n is the number of commits from your current branch you want to involve, in your case; 2

**`git rebase -i head~2`**

A text document will open, at the top of that are your 2 most recent commits.
In here, you can either change **`pick`** into **`d`** or just remove the lines from the document. This will delete the two commits from master (the two commits on this pr). Now you want to add in your other, better commit, and you do this by adding the line **`pick xxxxxx abcd...`**

**`pick 5f3f2a2 Implemented school immunity for creature from database`**

 below the 2 commits (or instead of), but before the comments start.

Then you save the document and close it. If something messed up and it's telling you it did not sucessfully rebase then enter the command **`git rebase --abort`** - Doing this ensures no changes from the failed rebasing are made to the pr at all.
If things went fine then you should be ready to push it to remote. You **have** to force push it or there will be merge conflicts.

**`git push -f`**

But you already know that probably.

Let's say that you maybe wanted to either squash or reorder some commits in another branch. you do this by using **`git rebase -i head~n`** - (you need to be touching up on at least 2 or more commits for it to make any sense, so n must be equal to or larger than 2 in this case) , but this time you change **`pick`** into **`f`** or **`s`**, depending if you wanted to save some of the commit name or message of the commit you are squashing. You always fix and squash **upwards** in the document, meaning you change the line of the commit you want to dissappear, into the commit above it. Reordering is as simple as taking a commit line and swapping it around with another. This may however cause merge issues and if that happens you may want to do a **`git rebase --abort`** here as well.

**Comment by cala** [comment]
I'd like to push this soon. If @sidsukana does not have the time to update/rebase the PR with his last changes, I suggest to merge it as it is and add the next changes in a next PR. Does this sound good?

**Comment by Phatcat** [comment]
I'd rather just one of us do a pr on his behalf instead; it is no issue at all for me to do it, I just hoped Sid would do it himself, by him learning to do it it may help him be able to pr and contribute even more of his work.

**Comment by sidsukana** [comment]
@cala @Phatcat i update PR, and repeat my post above

> this version with physical damage school immunity, includes wand problem

**Comment by sidsukana** [comment]
and you are rights, at last days does not have the time :)

**Comment by Phatcat** [comment]
@sidsukana If you do a `git rebase -i head~1` and drop the commit, you'll keep the changes ([this commit](https://github.com/cmangos/mangos-classic/pull/119/commits/5f3f2a2132004e5e0a80ea36737827c7fe46b3ae)) and get rid of that not so pretty 'merge branch 'x' of...'
You can see it's an empty commit by looking [here](https://github.com/cmangos/mangos-classic/pull/119/commits/e249d3d5529b11d32985851735e503797ed5c554), so there's no reason to hold onto it.

**Comment by sidsukana** [comment]
I all messed

**Comment by Phatcat** [comment]
Okay, so that removed all the commits... Sorry if this is a bit confusing.

If you do a `git rebase cmangos/master`, then a `git cherry-pick 5f3f2a2` and then a `git push -f` then this whole mess should be over you the pr should contain the relevant commit and nothing else. again, sorry if I only cofuse more than I help..

**Comment by sidsukana** [comment]
It seems that closed PR no longer open )

**Comment by Phatcat** [comment]
There you go

**Comment by sidsukana** [comment]
@Phatcat YEA!!! you are wizard xD

**Comment by Phatcat** [comment]
@sidsukana I only tried guiding you through a small part of what I consider to be the git jungle, you're the one who actually done some code work to improve the core here. This is all you =)

**Comment by cala** [comment]
Ok, I'll try to test this soon and provide feedback. :)

**Comment by sidsukana** [comment]
It fixes the results of spell hit by wand, discuss...

**Comment by sidsukana** [comment]
This way the total correction (this not only for PR), but some hackly

**Comment by cala** [comment]
I will test the whole PR soon, thank you. Probably tonight.

Could you tell us what you consider as a hack so we can look for another way to implement this, please?

**Comment by sidsukana** [comment]
Well, I think it's the same workaround as here https://github.com/sidsukana/mangos-classic/blob/master/src/game/Spell.cpp#L275
Now I do not see a more rational fix. Since the commonly used functions such as `GetSchool`, `GetSchoolMask`, `GetSpellSchoolMask` by which does not work to determine the damage school of wands

**Comment by cala** [comment]
I tested this last version tonight and everything that was supposed to be fixed was indeed fixed. Good job ! :+1: 

However, I think that the wand fix only fixes a small part of a bigger issue (and this is probably why you had to do it in a hackish way). Let me explain:
- give fire immunity to a NPC and attack it with fire wand: it is immuned
- give fire immunity to a NPC and attack it with a fire weapon: it takes damage (physical damage)
- give physical immunity to a NPC attack it with a fire weapon: it is immuned

This clearly shows two things:

1. the new immunity mechanics (first two commits) works as intended. This is nice ! :smile: 
2. the core does not handle elemental damage from weapon and the last commit (wand fix) only fixes a part of this issue

So, what I will do:
- Add the new school immunity mechanics by merging the first two commits. I will do it myself because the database structure is changed, so the core revision number must be increased (that did not happen in a while). I expect to merge them tonight or tomorrow
- open a new issue about elemental weapons not working and do a bit of research, with the last commit (wand fix) as a starting point.

**Comment by sidsukana** [comment]
@cala, I have developments for weapon elemental subdamage support by mityada
I will try to make a new PR on this issue in the near future

**Comment by cala** [comment]
Merged. Thank you! :+1: 

I've opened an issue (https://github.com/cmangos/issues/issues/957) about the elemental weapon damages being handled as physical. Your help is welcomed in this topic also! :smile:

**Pull request closed without merging**
