### PR TITLE
Fix questgiver greeting locales loading

### PR DESCRIPTION
**Pull request by mityada**
Use GetOrNewIndexForLocale to get correct locale index

### CODE REVIEW

**Comment by killerwife** [comment]
@mityada You synchronized locale loading for locales_questgiver_greeting with the other loading procedures?

**Comment by mityada** [comment]
@killerwife, yes. But synchronization was not the main reason. Your code assumed that all locales are always present and are in order. That's not true, so questgiver greeting localization was not working properly.

**Comment by killerwife** [comment]
Did you test this? I do not have a different locale available so I cannot verify the PR.

**Comment by mityada** [comment]
I did. I'm helping @M2us with Russian locale, he was the first to notice this bug.

**Comment by killerwife** [comment]
I will push this to other branches today.

**Pull request merged**
