### PR TITLE
add git_id to cmake build options (also clean out unneeded visual studio project files)

### PR DESCRIPTION
**Pull request by Phatcat**
pretty much the title

### CODE REVIEW

**Comment by cala** [comment]
As I don't use Visual Studio, I'd like to have feedback from another VS user or at least an explanation regarding this change before merging it.

**Comment by Phatcat** [comment]
I'm a visual studio user, this isn't needed since we use cmake to make our own visual studio project files now. This is leftovers from back when cmangos provided the project files.

**Comment by killerwife** [comment]
Last time I checked, git_id was not in cmake. So this needs a cmake addition before its removed.

**Comment by Phatcat** [comment]
It probably does yea.

**Comment by Phatcat** [comment]
Now git_id is a selectable build option in cmake.

**Pull request merged**
