### PR TITLE
Teach Sapphiron how to fly. (Naxx)

### PR DESCRIPTION
**Pull request by Yatzii93**
## 🍰 Pullrequest

Sapphiron needs additional code to do his proper fly animation and not be ground locked.
I figured @cala might appreciate this considering he's reworking naxx and it took me a little while to perfect this for Felmyst in Sunwell. 
### Proof

- None

### Issues

- Give Sapphiron wings.

### How2Test

- Do the boss fight until Sapphiron does his airbolt phase.

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by cala** [comment]
Great, thank you. :+1: 
This will indeed save me some times as this was one of the issues I've already identified with this fight.
This will also benefit to Onyxia encounter phase 2 where the boss is standing in the air instead of flying.

**Comment by cala** [comment]
@Yatzii93 I assume this is a direct port from TBC code because `UNIT_BYTE1_FLAG_FLY_ANIM` does not exist in Classic.

I will look at this.

**Comment by Yatzii93** [comment]
> @Yatzii93 I assume this is a direct port from TBC code because `UNIT_BYTE1_FLAG_FLY_ANIM` does not exist in Classic.

@cala yep! Apologies if it's not as helpful as I thought, I only work on the TBC core.

**Comment by cala** [comment]
No worries, just to be sure. :wink:

**Comment by killerwife** [comment]
I am gonna do a small possibly useless note. Nightbane and Onyxia are utterly different. That being said, Nightbane was in development when Sapphiron was in development. ^^

**Comment by cala** [comment]
I tested this PR on Classic and TBC. On TBC, it works fine: Sapphiron takes off, hover and nicely play his flying animation when casting spells and when being idle in the air and finally, he lands correctly.

However, on Classic, this does not work. Take off/landing are fine. Flying animation is played when casting spells, but when Sapphiron should be idle in the air he stands still as if on the ground instead of playing his flying/hovering animation. Basically, this looks like the same issue than with Onyxia encounter in phase 2.

It looks that we are missing the Classic equivalent of `UNIT_BYTE1_FLAG_FLY_ANIM` and we should investigate on this.

**Comment by killerwife** [comment]
As someone who raged at onyxia very recently, you will find that making these dragons work is extremely difficult. I hope to do another classic export round, and I will explain what I am on about. The code above did not work for onyxia even in TBC, even though the identical code works perfectly for nightbane and felmyst. I'll link you cala on the commit when I port it.

**Comment by cala** [comment]
I'm not surprised at all that having nice flying dragons in Classic is extremely difficult. Flying was not a real thing in Classic, so I guess Blizzard used workarounds for the handful of NPCs that should emulate fly rather that writing a full system for them...

I've merged this commit for code consistency with TBC with a few changes : I commented out the non-existing flag and I disabled flying/levitating/hovering when Sapphiron is on ground because he was hover towards his target instead of walking/running.

I'll be happy to update this part of the code once we have a working code for flying creatures in Classic, but in the meantime, I prefer to have things moving forward. :)

**Pull request closed without merging**
