### PR TITLE
Support for Gandling script

### PR DESCRIPTION
**Pull request by Zingzah**
Adds enums for Gandling Winter Veil check

### CODE REVIEW

**Comment by dagochen** [comment]
You can handle this by database. Just add entry in game_event_creature_data.

**Comment by cala** [comment]
Unfortunately, one cannot, as @Zingzah explained [here](https://github.com/cmangos/mangos-classic/pull/325#issuecomment-344424195). This only works for static spawns and Gandling is not one.

**Comment by killerwife** [comment]
Just use the spell guys.

**Comment by cala** [comment]
Closed in https://github.com/cmangos/mangos-classic/commit/cb1114ce76c53117fc6613438578caaee0cfd3a5
Thank you.

**Pull request closed without merging**
