### PR TITLE
Implement SMSG_PVP_CREDIT opcode

### PR DESCRIPTION
**Pull request by sidsukana**
It's PvP frame on honorable kills

### CODE REVIEW

**Comment by Phatcat** [comment]
Could you possibly go a bit more into detail with this does exactly? How can I best see the changes in effect?

**Comment by dagochen** [comment]
From what the code changes I would try to do a dishonorable kill ...?

**Comment by Phatcat** [comment]
is there something wrong with the current way we do dishonorable kills? - but thanks, I'll try that.

**Comment by dagochen** [comment]
Thats something you should ask @sidsukana :) Maybe dishonorable kills were not shown in combatllog or so....? Dunno...never checked that^^

**Comment by Phatcat** [comment]
would be nice to know exactly what I was looking at, the information is a bit sparse on this one.

**Comment by sidsukana** [comment]
Kill honorable target in PvP - popup frame with icon and name of target rank.
For example https://youtu.be/IyeoT1owdFo?t=508 HK:Senior Sergeant

**Comment by Phatcat** [comment]
> popup frame with icon and name of target rank.
Say no more, I don't even have to look at the video, I know exactly what you are talking about now. Don't we do those at all on cmangos? If that is the case then, nice job, sid!

How was this handled for TBC? It showed the rating of your opponent if your opponent was a player, no? Or am I just imagining things?

**Comment by sidsukana** [comment]
> Say no more, I don't even have to look at the video, I know exactly what you are talking about now. 
> Don't we do those at all on cmangos? If that is the case then, nice job, sid!

PvP system in ТВС and wotlk was greatly changed in comparison with the classic. I know that in the TBС and wotlk also have a pop-up frames, but not sure that they have the same structure in the classics.

(If I understand you :))

**Comment by killerwife** [comment]
We do not need this :) The packets version in TBC is implemented properly.

**Comment by Phatcat** [comment]
I'm guessing it didn't change much between TBC and Wrath? (that it's properly implemented for wrath as well)

**Comment by killerwife** [comment]
Well the only reason this isnt implemented is because of wotlk branch. So nope.

**Comment by Phatcat** [comment]
Alright so I tested this out, and sadly I did not get the pvp pop-up...

I took my freshly created warrior from both factions, gave them a few levels, teleported the to the same area, set them both to pvp, then I set one to kill the other; no pop-up..

It is very much supposed to pop up even if your kill has no rank at all https://www.youtube.com/watch?v=FoAsyv6QpSs (0:30)

**Comment by Phatcat** [comment]
No wait scratch that, it works fine, there was a level difference between them making the target gray....

**Comment by Phatcat** [comment]
Merged with https://github.com/cmangos/mangos-classic/commit/979a9a54e5e94e0f034b6de1f027c57e9b2aa46d

**Pull request closed without merging**
