### PR TITLE
researched/updated some SpellAttribute flags

### PR DESCRIPTION
**Pull request by schell244**
## 🍰 Pullrequest

I did some research and updated some spell dbc flags.

    1. converted spell.dbc (5875) to sql (using WDBX Editor) in order to properly filter, etc...
    2. searched for spells ids which only had one certain flag (=SpellAttributes)
    3. put spell id in wow head: https://classic.wowhead.com/spell=XXX
    4. wowhead did display what the flag stands for (in most cases)
    5. converted flag from decimal to hex and compared what CMangos had assigned to it

### Todo / Checklist

Newly added flags need to be tested/confirmed:

SPELL_ATTR_PERIODICALLY_TRIGGER   
SPELL_ATTR_EX_STOPS_AUTO_ATTACK 
~~SPELL_ATTR_EX2_MODIFY_THREAD~~
SPELL_ATTR_EX4_REAL_TIME_DURATION ( taken from VMangos repo)

### CODE REVIEW

**Comment by killerwife** [comment]
SPELL_ATTR_EX2_MODIFY_THREAD and SPELL_ATTR_COOLDOWN_AFTER_AURA_FADES are definitely not accurate. The second one also adds cooldown after lets say gameobject despawn or summoned creature despawn (wotlk ghoul). The first one is SPELL_ATTR_EX2_UNAFFECTED_BY_AURA_SCHOOL_IMMUNE and I proved that to be the meaning in client. Its gonna be in one of my exports. The rest, well, naming them is one thing, but you should also add its implementation when you name it. Or hint where its used in client.

**Comment by schell244** [comment]
Thank you for checking this PR so fast. I'll restore SPELL_ATTR_EX2_MODIFY_THREAD and SPELL_ATTR_COOLDOWN_AFTER_AURA_FADES to it's previous values. Sadly I can't add the implementation for the spells myself, my C++ knowlegde is very basic. Feel free to do whatever you want with this PR - I just wanted to share my researched results and hoped that it might be useful for further development.

**Comment by killerwife** [comment]
Very well. Add TODOs to the enum then. I will resolve this later.

**Comment by Daribon** [comment]
I've looked into this a bit and I don't know where you are getting the npc and player part of on next swing.
Here is spell attributes from wow development (probably dated somewhere around 2003:
nomacs_nHfQx37HcX

And from the tbc classic (the remaster client) [enumeratedstring.db2](https://wow.tools/dbc/?dbc=enumeratedstring&build=2.5.1.39603#page=5):
firefox_lBJHSxWouI

SPELL_ATTR_ON_NEXT_PLAYER_SWING = 0x00000004,// 2 On next swing (players)
should most likely be
SPELL_ATTR_ON_NEXT__SWING_ND = 0x00000004,// 2 On next swing (no damage)

SPELL_ATTR_ON_NEXT_NPC_SWING = 0x00000400,// 10 on next swing (npcs)
should be
SPELL_ATTR_ON_NEXT_SWING = 0x00000400,// 10 on next swing

**Comment by schell244** [comment]
I was not aware of the existence of actual development screenshots regarding the flags, which is obviously a more reliable source. As I mentioned above, my source was `https://classic.wowhead.com/spell=XXX`. 
players
npc

**Comment by killerwife** [comment]
https://wow.tools/dbc/?dbc=enumeratedstring&build=2.5.1.38093

**Comment by schell244** [comment]
Very interesting, thank you. I guess this makes this PR superfluous?

**Comment by killerwife** [comment]
Well, until actual implementations are done, this PR is a good reminder.

**Pull request closed without merging**
