### PR TITLE
5/8 set bonus is broken for hunter/warlock in T1 and T2 

### PR DESCRIPTION
**Pull request by TarasHots**
Current PR includes fixes for resistance, hp aura bonus and small class-related fixes when pet wasn't affected by set bonus aura(when pet was tamed with 5/8 or 5/8 was weared prior to pet summon).

Fixes https://github.com/cmangos/issues/issues/640

### CODE REVIEW

**Comment by TarasHots** [comment]
Could you guys check my commits, especially last one? Not sure is it viable, and want to hear your opinion on that. Set bonuses works great. Applying, removal, sets changes, combat, regeneration - everything works fine

**Comment by sidsukana** [comment]
May be better:
```
case 21926: // Nature's Ally (T1 5/8 bonus)
case 21928: // Nature's Ally (T2 5/8 bonus)
case 21741: // Demonic Ally (T1 5/8 bonus)
case 21922: // Demonic Ally (T2 5/8 bonus)
{
    Pet* pet = triggerTarget->GetPet();

    if (SpellAuraHolder* holder = pet->GetSpellAuraHolder(trigger_spell_id);
        holder->SetAuraDuration(4000);

    return;
}
```

**Comment by TarasHots** [comment]
Could you guys share your opinion about these changes? I thought about another thing: parent spell have duration for 3 sec, child spell have 4 sec. It looks like, looks like parent should keep child one somehow and in some way. I guess that duration reset is one of possible ways to do it. I would say that my custom case for 5/8 sets should be separated and generalized for similar auras. Do you have any ideas? That thing can be done as improvement...

**Comment by Phatcat** [comment]
If it can be generalized without 'hacking' it into the other aura functions or mess with durations of auras this does not apply to, then I only see it as an improvement. But if it requires setting up special cases to handle on a per spell basis in the other functions just to avoid the special cases here then it is not a good idea.

But besides that the code itself looks good.

**Comment by cyberium** [comment]
Well @Phatcat resumed what i think. Either we do something in wrong in general way we handle this case or this patch may be rewrited in more general way using some flags.
I realy want to get rid of all those cases. So if no one give an alternative i think this patch could be reasonable.

**Comment by sidsukana** [comment]
Here is a list of matched spells for this rule taken by qspellwork with filter

> spell.Attributes & SPELL_ATTR_PASSIVE &&
> spell.Duration == -1 &&
> ((spell.EffectAmplitude(0) > 0 && spell.TriggerDuration(0) > 0 && spell.EffectAmplitude(0) < spell.TriggerDuration(0)) ||
> (spell.EffectAmplitude(1) > 0 && spell.TriggerDuration(1) > 0 && spell.EffectAmplitude(1) < spell.TriggerDuration(1)) ||
> (spell.EffectAmplitude(2) > 0 && spell.TriggerDuration(2) > 0 && spell.EffectAmplitude(2) < spell.TriggerDuration(2)))

```
758 | Firestone Passive (Rank 1)
3717 | zzOLDSuccubus Link
4044 | Target Dummy Passive
4048 | Advanced Target Dummy Passive
4972 | Healing Ward V Passive
5111 | Living Flame Passive
5608 | Healing Ward Passive
5672 | Healing Stream (Rank 1)
5677 | Mana Spring (Rank 1)
5707 | Lifestone Regeneration
5728 | Stoneclaw Totem Passive (Rank 1)
5733 | zzOLDInvisibility Totem Passive (Rank 1)
6276 | Healing Ward IV Passive
6371 | Healing Stream (Rank 2)
6372 | Healing Stream (Rank 3)
6397 | Stoneclaw Totem Passive (Rank 2)
6398 | Stoneclaw Totem Passive (Rank 3)
6399 | Stoneclaw Totem Passive (Rank 4)
6474 | Earthbind Totem Passive
6498 | Feed Sarilus Passive
6820 | Corrupted Agility Passive
6821 | Corrupted Strength Passive
6822 | Corrupted Stamina Passive
6823 | Corrupted Intellect Passive
7667 | Foul Odor
8145 | Tremor Totem Passive
8167 | Poison Cleansing Totem Passive
8172 | Disease Cleansing Totem Passive
8188 | Magma Totem Passive (Rank 1)
8229 | Flametongue Totem Passive (Rank 1)
8251 | Flametongue Totem Passive (Rank 2)
8266 | Lava Spout Totem Passive (Rank 1)
8350 | Fire Nova (Rank 1)
8434 | Leech Pulse
8443 | Fire Nova (Rank 1)
8504 | Fire Nova (Rank 2)
8505 | Fire Nova (Rank 3)
8508 | Fire Nova (Rank 2)
8509 | Fire Nova (Rank 3)
8515 | Windfury Totem Passive (Rank 1)
8833 | Ward of Zanzil Passive
9769 | Radiation
10425 | Stoneclaw Totem Passive (Rank 5)
10426 | Stoneclaw Totem Passive (Rank 6)
10460 | Healing Stream (Rank 4)
10461 | Healing Stream (Rank 5)
10491 | Mana Spring (Rank 2)
10493 | Mana Spring (Rank 3)
10494 | Mana Spring (Rank 4)
10524 | Flametongue Totem Passive (Rank 3)
10582 | Magma Totem Passive (Rank 2)
10583 | Magma Totem Passive (Rank 3)
10584 | Magma Totem Passive (Rank 4)
10609 | Windfury Totem Passive (Rank 2)
10612 | Windfury Totem Passive (Rank 3)
11087 | Ward of Zum'rah Passive
11310 | Fire Nova (Rank 4)
11311 | Fire Nova (Rank 5)
11312 | Fire Nova (Rank 4)
11313 | Fire Nova (Rank 5)
11901 | Healing Ward V Passive
11966 | Fire Shield
12507 | Atal'ai Skeleton Totem
12743 | Immolation
13377 | Fire Shield
15127 | Summon Burning Imp
15697 | zzOLDWisdom Aura (Rank 1)
15789 | Moonflare
15872 | Superior Healing Ward Passive
16191 | Mana Tide (Rank 1)
16192 | zzOLDMana Tide (Rank 1)
16388 | Flametongue Totem Passive (Rank 4)
17328 | Aura of Penitence
17355 | Mana Tide (Rank 2)
17356 | zzOLDMana Tide (Rank 2)
17360 | Mana Tide (Rank 3)
17361 | zzOLDMana Tide (Rank 3)
17625 | Unholy Aura
17945 | Firestone Passive (Rank 2)
17947 | Firestone Passive (Rank 3)
17949 | Firestone Passive (Rank 4)
18148 | Static Field
18268 | Fire Shield
18764 | Fungal Regrowth (Rank 1)
18978 | Ice Totem
19230 | Panda
19483 | Immolation (Rank 1)
19626 | Fire Shield
19809 | Masterwork Target Dummy Passive
20556 | Golemagg's Trust
20969 | Vitality (Rank 1)
21168 | Vitality (Rank 1)
21733 | Spore Tree Trigger
21741 | Demonic Ally
21857 | Lava Shield
21861 | Gizlock's Dummy Taunt
21922 | Demonic Ally
21926 | Nature's Ally
21928 | Nature's Ally
21938 | Nature's Ally
22049 | Testing Totem Passive (Rank 1)
22391 | Demon Portal
22441 | Growing Flames
22781 | Thornling
22787 | Irritating Spores
23003 | Alarm-o-bot
23184 | Mark of Frost
23211 | Copy of Increased Mana Regen
23245 | Corrupted Stamina Passive
23792 | Stoneclaw Totem Passive TEST
24344 | Bloodlord's Aura
24620 | Portal of Madness
24777 | Dream Fog
24853 | Mana Spring
25001 | Spirit Totem
25041 | Mark of Nature
26176 | Unseen Path Pet Bonus
26744 | Poisonous Blood
27038 | Increased Pet Health +3%
27043 | Increased Pet Crit +2%
27206 | Increased Pet Damage +3%
27225 | Increased Pet Armor +10%
27747 | Steam Tank Passive
28097 | Stalagg Tesla Passive
28109 | Feugen Tesla Passive
28156 | Disease Cloud
28298 | Lightning Totem
28356 | Copy of Disease Cloud
28357 | Copy of Disease Cloud
28370 | Toxic Gas
28384 | Portal of Shadows
28534 | Chill
28756 | Stalker's Ally
29327 | Sapphiron's Wing Buffet
29897 | Guardian of Icecrown Passive
30074 | Toxic Gas
30243 | Plague Wave
30799 | Regeneration (Rank 1)
30800 | Regeneration (Rank 2)
30801 | Regeneration (Rank 3)
```

**Comment by sidsukana** [comment]
can even try to correct filter

**Comment by ROKB** [comment]
resistance aura not work

**Comment by TarasHots** [comment]
@ROKB better provide proves. [Warlock](https://imgur.com/a/xtuLv) and [Hunter](https://imgur.com/a/wqJLL)

**Comment by ROKB** [comment]
@TarasHots  oh sorry i miss understand :) work fine

**Comment by TarasHots** [comment]
@ROKB its okay). I've started work on improvements, but don't have so much time atm. My current suggestion is to fix set bonuses + all similar spells using 'not real applying' way. I've tried to remove and apply aura continiously, but it the same effect as bugged one. So I guess, if parent spell is still ticking, we should reapply all bonuses, but without real apply and do not remove current effects. Not sure how it will work, but gonna try that soon

**Comment by Phatcat** [comment]
@TarasHots What's the status on this?

**Comment by killerwife** [comment]
The keep triggered aura when parent aura is active is I think a bad approach. The reason why the parent has 3s period and child has 4s is because its applied to pet, and whenever when its applied again, it should just remove the previous one, and nothing changes. From my understanding this "constant" rewrite of stats should occur all the time and should not be a problem. Therefore hacking the duration in any way is seriously bad.

**Comment by killerwife** [comment]
Also, previous behaviour is that only pets and players have base stats, and during refactoring, you changed to "everything has base stats" suddenly, on what observation I might ask?

**Comment by killerwife** [comment]
To expand on my previous nonsense, it is quite apparent to me that SPELL_AURA_MOD_STAT should be always "refreshed" instead of "removed - recast", Just try spamcasting Power Word: Fortitude. (hint: when at full life, you should stay at full life). Make it into a nice general behaviour thingy and then after refactoring and squashing this can be added to cmangos I think :)

**Comment by dagochen** [comment]
a call of refreshholder should work as well, instead of hardcoding the refreshing time.

**Comment by killerwife** [comment]
Yes you are right, but this is a global problem not a problem with this particular spell. I.e. for several whole schools of spell auras

**Comment by cyberium** [comment]
So we still have problem with this but this is not the solution

**Pull request closed without merging**
