### PR TITLE
Game/Spell: Handle SPELL_FAILED_NOTHING_TO_DISPEL

### PR DESCRIPTION
**Pull request by Phatcat**
By @Caydan

---
This change is [Reviewable](https://reviewable.io/reviews/cmangos/mangos-classic/180)

### CODE REVIEW

**Comment by Phatcat** [comment]
Anyone else care to look at this? In my opinion this looks decent.

**Comment by dagochen** [comment]
What is the problem which shall be fixed by this?

**Comment by Phatcat** [comment]
As I understand it currently the player is not informed properly if there is no no debuff to remove when using dispel effects, as in that error message is not implemented anywhere in the code, it's only defined:

https://github.com/cmangos/mangos-classic/search?utf8=%E2%9C%93&q=SPELL_FAILED_NOTHING_TO_DISPEL

We do get a message that 'Nothing to dispel', so....

**Comment by Phatcat** [comment]
This seems to be an issue exclusive to classic, even though SPELL_FAILED_NOTHING_TO_DISPEL is nowhere to be found besides in the defines.
It seems to be handled fine on tbc and wrath (perhaps the check was moved client side, or I am missing something obvious perhaps)

you can reproduce an error by making a druid
`.learn 8946`
cast it on yourself
it shouldn't allow it to be cast, but rather display 'Nothing to disspel'
With this patch it displays that when appropriate.
On tbc and wrath branches, again, it seems to already act appropriate, even though that spell cast result is not handled anywhere serverside..

**Pull request merged**
