### PR TITLE
Enable high-res extraction in ExtractResources.sh

### PR DESCRIPTION
**Pull request by Muehe**
See https://github.com/cmangos/issues/issues/1877 for related discussion.

* Changed shebang to point to `sh` instead of `bash` across all versions
* Added changes by @adellaci to enable high-res extraction
* Changed description of two user inputs to include the expected options

### CODE REVIEW

**Comment by adellaci** [comment]
```
cmake ~/mangos/mangos-classic -DCMAKE_INSTALL_PREFIX=~/wow-servers/mangos-server-classic -DBUILD_EXTRACTORS=ON -DBUILD_PLAYERBOT=ON -DPCH=1 -DDEBUG=0 -DBUILD_RECASTDEMOMOD=ON

Tue Feb 19 19:48:57 EST 2019
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mangos/build-classic
Tue Feb 19 19:49:00 EST 2019
```
```
make -j12

Tue Feb 19 19:49:00 EST 2019
[100%] Linking CXX executable mangosd
[100%] Built target mangosd
~/build-classic$ date
Tue Feb 19 19:53:56 EST 2019
```

**Comment by adellaci** [comment]
```
Sun Feb 17 16:21:50 EST 2019: Start extracting dataz for MaNGOS
DBC and map files will be extracted
Vmaps will be extracted
Mmaps will be extracted with 8 processes

Sun Feb 17 16:21:50 EST 2019: Start extraction of DBCs and map files...
Sun Feb 17 16:22:13 EST 2019: Extracting of DBCs and map files finished

Sun Feb 17 16:22:13 EST 2019: Start extraction of vmaps...
Sun Feb 17 16:22:47 EST 2019: Extracting of vmaps finished
Sun Feb 17 16:22:47 EST 2019: Start assembling of vmaps...
Sun Feb 17 16:22:55 EST 2019: Assembling of vmaps finished

Sun Feb 17 16:22:55 EST 2019: Start creating MoveMaps
Used params: --silent --offMeshInput offmesh.txt
Detailed log can be found in MaNGOSExtractor_detailed.log

Sun Feb 17 17:14:41 EST 2019: Finished creating MoveMaps
Sun Feb 17 17:14:41 EST 2019: Finished creating MoveMaps
```

**Comment by cala** [comment]
@Muehe Since you have push rights now, I let you merge this. If you don't feel to do it, I'll handle this next round. As you wish! =)

**Comment by Muehe** [comment]
@cala I'm on a spontaneous weekend trip right now, will merge it myself when I get back.

**Comment by cala** [comment]
At your leisure! 😉

**Pull request closed without merging**
