### PR TITLE
Rewrite Config to "pimpl" idiom

### PR DESCRIPTION
**Pull request by sidsukana**
It solve warning C4251

### CODE REVIEW

**Comment by sidsukana** [comment]
Restore STD using.

**Comment by Phatcat** [comment]
So... what does this do exactly? besides solving a warning?

**Comment by sidsukana** [comment]
Only C4251, but only for Config class (as example for resolve some warnings wihout disable)

**Comment by cyberium** [comment]
no more needed Thanks @sidsukana for the effort

**Pull request closed without merging**
