### PR TITLE
怎么又差异

### PR DESCRIPTION
**Pull request by solo0755**
### Proof

- None

### Issues

- None

### How2Test

- None

### Todo / Checklist

- [X] None

### CODE REVIEW

**Comment by berserkingyadis** [comment]
Hi, please fill out the PR template, so that we know what we are looking at here. 

Also, try to use english to describe this, If possible.

**Comment by bendol-i3** [comment]
Seems to be something similar to the import script I submitted recently.

**Comment by BenDol** [comment]
Seems to be something similar to the import script I submitted recently.

**Comment by cala** [comment]
Closing this PR as we have no feedback. If @solo0755 still want to submit a PR, please use our PR template - in English - so we can properly look a it.

**Pull request closed without merging**
