### PR TITLE
[WIP] Extreme Makeover AI Edition 1.0 - Real Stupidity

### PR DESCRIPTION
**Pull request by Phatcat**
I have plans to make our core generically support creature classes; currently all mobs behave in one way; like spellcasting rambos.... and so the fun begins...

---
This change is [Reviewable](https://reviewable.io/reviews/cmangos/mangos-classic/166)

### CODE REVIEW

**Comment by Phatcat** [comment]
Yes, I basically just used the WIP tag as an excuse to correct the title. Don't hate on me ^^

**Comment by Phatcat** [comment]
@cala This one is also yet another one for you sadly; it should however fix some of the issues reported on Pet patch along with some other AI stuff.

**Comment by Phatcat** [comment]
@cyberium
Now that you have a bit more time for this sort of thing again (which is just lovely to see <3) then I would love for your thoughts on this as well.

**Comment by Phatcat** [comment]
@cala https://github.com/cmangos/mangos-classic/pull/166/commits/ab6660ac1e1102dc8864fdea36b369ba44a489f4 is the commit that should hopefully take care of issues regarding pets with EventAI set.

Also @cyberium @xfurry @VladimirMangos @killerwife What do you guys think?
I want to expand on this by seperating the behaviour in creatureEventAI by the 3 unit classes, instead of having one behaviour for them all. Mages and paladins should not just rush in to melee their target, as evident by basically any old warcraft video.

**Comment by cyberium** [comment]
@Phatcat all these change sound reasonable. However i cannot test all the possible cases where this may broke something. There is too much of them. I assume you already did necessary test and checked the improvement. So i think you just have to push and be ready to any following opened issue related to it.

**Comment by xfurry** [comment]
Overall the changes look reasonable, but we should test this properly.
On Wotlk, there are come complex scripts, which might be impacted.

**Comment by cala** [comment]
> @cala ab6660a is the commit that should hopefully take care of issues regarding pets with EventAI set.

@Phatcat great to see those changes, they looks very interesting. But I'm leaving for holidays today, so I won't be able to test this until I return in three weeks. So, don't wait for me if you get good feedback in the meantime.

**Comment by Phatcat** [comment]
Looking further into creatureEventAI part of this right now.

Most of these changes are related to owner, and I added a check to see if we use dynamic movement before setting the creature to move anywhere locally, also I found that we are overwriting the unit AI to not use a scripted AI if the creature is a pet, which of course has to be changed for any of these changes to actually make sense.

Testing against this lovely script by @cala

> `DELETE FROM `creature_ai_scripts` WHERE `creature_id` = 15720;`
`INSERT INTO `creature_ai_scripts` VALUES`
`(1572001, 15720, 14, 0, 100, 1, 1000, 40, 15000, 18000, 11, 11986, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Timbermaw Ancestor - Cast Healing Wave on Friendlies'),`
`(1572002, 15720, 0, 0, 100, 1, 0, 40, 3400, 4800, 11, 9532, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Timbermaw Ancestor - Cast Lightning Bolt');`

> `UPDATE creature_template SET AIName='EventAI' WHERE Entry=15720;`

**Comment by Phatcat** [comment]
@cala Have a great trip if you're going somewhere :3

**Comment by Phatcat** [comment]
@cala Nothing here to look into anymore `*sadface*` (for the time being); I removed anything related to eventAI and pets since I can't even get pets to use eventAI at all, and some of the other changes I included with my latest pet patching, so currently there's not much to review or look at; perhaps maybe the thing about not evading in dungeons but that commit surely needs more work.

**Comment by cala** [comment]
I have enough things to take care of at the moment, don't worry. ;)

**Pull request closed without merging**
