### PR TITLE
Alterac Valley fixes

### PR DESCRIPTION
**Pull request by celguar**
## 🍰 Pullrequest
Fixes for current Alterac Valley code to make basic functions work. I know current BG scripts are considered outdated and we want total rewrite using spawn groups or whatever, but at least we can have a semi-working BG until it's rewritten.
Most fixes are from vmangos.

Fixes included:
Fix GY act like towers and vice versa
Fix WorldState update for Snowfall GY (from vmangos)
Initialize additional variables (fixes crazy numbers in "leutenants killed" in BG scores)
Fix Alterac Valley mines being not neutral from start
Fix fires not spawning on bunker after captain kill
Fix "towers defended" not working in BG score

Note: mines fix doesn't work without DB fix, will make a PR with it.

### CODE REVIEW

**Comment by killerwife** [comment]
I personally have 0 problems with the current BG scripts. The only real thing I have a problem with is unifying the worldstate management in the future. As such, no problem with your PR really. Make the DB part pls.

**Comment by celguar** [comment]
I'm sorry, Mines DB fix is required for tbc, not classic. I'll make a pr later for tbc core/db too. But I'll make a small PR to classic db too

**Comment by killerwife** [comment]
Also perhaps check this related issue https://github.com/cmangos/issues/issues/1400 I think it works also in vmangos

**Comment by cala** [comment]
No remarks for my part about this PR. Aside from the small conflict in `BattleGroundAV.cpp` is it fine that I merge this?

**Comment by celguar** [comment]
Though it's one line so maybe you can resolve it

**Comment by celguar** [comment]
Merge conflict solved but merge commit appeared in PR. I hope it's not a problem :[

**Pull request closed without merging**
