### PR TITLE
Implement playerRank in defensive channnels.

### PR DESCRIPTION
**Pull request by Laizerox**
Not sure what's up with github PR can't select only commit :( anyway as per title says!

### CODE REVIEW

**Comment by stfx** [comment]
Thanks, looks great. Can be integrated after it was tested;)

**Comment by cala** [comment]
I can test it this afternoon or evening. Classic only or master/tbc also ?

**Comment by stfx** [comment]
> I can test it this afternoon or evening. Classic only or master/tbc also ?
This only applies to classic

**Comment by stfx** [comment]
Thanks, in https://github.com/cmangos/mangos-classic/commit/49c3206461a9808ba19a2a76a241fd6b98e19a4a

**Pull request closed without merging**
