### PR TITLE
The Missing Diplomat part 16

### PR DESCRIPTION
**Pull request by qprquo**
Hi guys , this is my attempt to script the Missing diplomat quest.
This is my first script. I know a code is awful so this PR's purpose is to ask your advice, guys,
how to do it properly and what is the best way to implement such features as despawning original NPCs like Jaina, Tervosh or
Pained and how to add hendel's guards, how to link them with Hendel (i just tried to summon them, but i couldnt achive fleeing on last phase)

### CODE REVIEW

**Comment by qprquo** [comment]
Ok ,I'll just close it .Seems nobody interested

**Comment by killerwife** [comment]
People usually respond in a week or month from posting. Everyone is busy with their side projects and contributions take time (@cala usually does more at once) We apppreciate your contribution/feedback but you need to be patient in return.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: qprquoSent: Monday, March 27, 2017 00:10To: cmangos/mangos-classicReply To: cmangos/mangos-classicCc: SubscribedSubject: Re: [cmangos/mangos-classic] The Missing Diplomat part 16 (#273)Ok ,I'll just close it .Seems nobody interested

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cmangos/mangos-classic","title":"cmangos/mangos-classic","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cmangos/mangos-classic"}},"updates":{"snippets":[{"icon":"PERSON","message":"@qprquo in #273: Ok ,I'll just close it .Seems nobody interested"}],"action":{"name":"View Pull Request","url":"https://github.com/cmangos/mangos-classic/pull/273#issuecomment-289320447"}}}

**Comment by Rushor** [comment]
could you please reopen the issue? the fix looks nice

**Comment by qprquo** [comment]
I going to fix few things then I'll reopen it

**Comment by cala** [comment]
I'm also interested by this PR. 😉 
As @killerwife said, I already have many things in the pipe but will definitely look at this. Thanks for your contribution.

**Comment by qprquo** [comment]
I'll plan to make original Jana, Pained and Tervosh invisible during a quest event.

**Comment by cala** [comment]
Hi, I hope to be able to have a look at this during the week. Do you have videos or other kind of sources that could help me understand a bit more this quest and what is supposed to happen, please?

**Comment by qprquo** [comment]
- https://www.youtube.com/watch?v=6XeuwJnqSd4 Wotlk video
- https://www.youtube.com/watch?v=DjLvJElJP6U TBC times video

According to the TBC video on the last phase  when Tervosh arrives guards start flee and when Tervosh cast spell on Hendel , Hendel despawns and guards despawn too

**Comment by cala** [comment]
Thank you for the videos and recent updates. I had more work than expected last week and I had to reschedule my review of this PR. I expect to have a look at this the coming week.

Sorry for the delay.

**Comment by kampeador** [comment]
Check out my implementation of this event. I've took some spawn coords from this script.
My script is heavily commented and i've spent ~15 hours on debugging trying to broke it.
https://github.com/kampeador/server/commit/334be0d4b62acba0bdc254488fb22ba1efb20522
https://github.com/kampeador/server/commit/678dff027b1e90406b14673d9b7281c1daf306df
There are some minor issues left.

I am rewriting full Missing Diplomat quest chain and scripts for quests(1640, 1249) are almost ready.

Enjoy.

**Comment by cala** [comment]
Thank you for the update. Still did not manage to have the time to look in depth at this PR but will do.

**Comment by kampeador** [comment]
My implementation of this event has reached 100% blizzlike status. All features are implemented. There will be a ton of changes. I'll upload them soon.

**Comment by cala** [comment]
I have a few backports and clean-up to do for the database, and then I handle this PR/script.

**Comment by cala** [comment]
Closed/merged by/in https://github.com/cmangos/mangos-classic/commit/8e44ff736bf95796dcbf6fa260478ad0ed54e9b9

Thank you @qprquo and @kampeador : I've implemented the script based on your research and work but with a different approach. I moved all the speech and visual parts to DBScript where it is easier to handle. This way I could rely on the core for most of the basic AI operation and avoid having to override it with all the extra code this implies.
👍

**Pull request closed without merging**
