### PR TITLE
[z2703] Remove duplicate info from creature_template

### PR DESCRIPTION
**Pull request by Phatcat**
creature_template contains a lot of duplicate info.

This removes Most things to do with ranged and streamlines faction for both ally and horde.

@Cyberium @cala @Tobschinski @killerwife @Grz3s

### CODE REVIEW

**Comment by killerwife** [comment]
The data is not duplicate.
    UNIT_FIELD_BASEATTACKTIME                 = OBJECT_END + 0x008D, // Size: 2, Type: INT, Flags: PUBLIC
    UNIT_FIELD_RANGEDATTACKTIME               = OBJECT_END + 0x008F, // Size: 1, Type: INT, Flags: PRIVATE

    UNIT_FIELD_ATTACK_POWER                   = OBJECT_END + 0x00CC, // Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    UNIT_FIELD_RANGED_ATTACK_POWER            = OBJECT_END + 0x00CF, // Size: 1, Type: INT, Flags: PRIVATE, OWNER_ONLY
    UNIT_FIELD_MINRANGEDDAMAGE                = OBJECT_END + 0x00D2, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY
    UNIT_FIELD_MAXRANGEDDAMAGE                = OBJECT_END + 0x00D3, // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER_ONLY

The only duplicate thing is:


-  `FactionAlliance` smallint(5) unsigned NOT NULL DEFAULT '0',
--
  |   | -  `FactionHorde` smallint(5) unsigned NOT NULL DEFAULT '0',
  |   | +  `Faction` smallint(5) unsigned NOT NULL DEFAULT '0',

But gotta first figure out why it was designed that way in the first place.

**Comment by Phatcat** [comment]
https://1drv.ms/i/s!Agpa05rA5GSClWUWxZpwY3kaNbI2

nothing with rangedattackspeed
nothing with rangedattackpower
nothing with rangeddamage

**Comment by Phatcat** [comment]
is the value kept in rangedmin and rangedmax ever going to be different than what is kept in meleemin and meleemax? from a template perspective? When we look at a ranged mob like the gurubashi axe thrower or the hakkari shadow hunter, both of them have 0 in min and max ranged damage (https://github.com/cmangos/classic-db/commit/971f0aa5eeb107908de7f2f30ed76aca96a4af4c). This is because their dedicated spells takes care of their ranged damage. Is there any mob that does not handle it's ranged damage through a dedicated spell?

is there any particular reason we are storing attack power in both creature_template and creature_template_classlevelstats? is rangedattackpower ever going to matter if min and max fields will always be 0 for mobs?

**Comment by killerwife** [comment]
The answer is very bad and very uninformative, but essentially these values come from sniffs and sniffs only. CLS is incomplete and needs to be extended to damage fully as well, but that is an unfinished concept. The person to ask about that is @cyberium . The removal of those fields cant be justified until all of that research and development is finished.

That being said, ask around for FactionAlliance and FactionHorde, ever since I came aboard I havent seen it being utilized.

**Comment by Phatcat** [comment]
Is there any creature which does NOT have 0 in UNIT_FIELD_MINRANGEDDAMAGE and UNIT_FIELD_MAXRANGEDDAMAGE (which is sniffed as you say) ?

> CLS is incomplete and needs to be extended to damage fully as well, but that is an unfinished concept.

Once again, that is outside the scope of what I'm proposing here. I am not proposing to remove min and max damage altogether. This change should not break or change a single mob functionality wise.

>  The person to ask about that is @cyberium

And I did tag him, didn't I?

> The removal of those fields cant be justified until all of that research and development is finished.

Is there anything I can work on at all or is everything in one big state of 'in development' blocking out any non core developer?

**Comment by killerwife** [comment]
I actually have a really good suggestion. SummonCreature function enables us to create temporary summons in C++ or SD2 alike. Recent evidence has uncovered that a tempsummon can have custom UnitFlags, NPCFlags or Faction. We need to add a table lets say called dbscript_tempsummon_settings which will enable us to make "templates" for tempsummons and set any parameter. It needs to be loaded in C++, and used in EAI and DBScripts and the UnitFlags, NPCFlags or Faction need to be added to SummonCreature function. Most likely need to create a C++ struct for it, now that the parameter count is getting insanely high, and also a wrapper for it. So far I know 6 scripts where this is needed, and I am sure WOTLK will need it even more.

FactionHorde, FactionAlliance seems to be used in Western Plaguelands for a spectral gryphon master who changes factions based on who is controlling the outpost (outdoor pvp). So it seems its used after all. - worth researching further

For the other unit fields, I tried asking around and we havent found enough legacy information to know why they were implemented, and removing something we dont know why it was added in the first place, is a bad idea.

**Comment by cyberium** [comment]
Thank you for this. However you are wrong. Creature can have both melee and range data with differents values. So wee need to have both set somewhere. Actualy @killerwife said what you need to know. We keep all sniffed data for now, they are precious.
For CLS even when it will be fully implemented iam not sure if it will be wise to remove not more needed data.

**Comment by Phatcat** [comment]
> Creature can have both melee and range data with differents values.

[15:42] <Tobschinski> andi havent seen yet that meleeattackspeed is different from rangedattackspeed
[15:42] <Tobschinski> in sniffs
[15:42] <Tobschinski> unless there's auras
[15:42] <Tobschinski> so it makes sense to only store one of them in c_template

> https://1drv.ms/i/s!Agpa05rA5GSClWUWxZpwY3kaNbI2
nothing with rangedattackspeed
nothing with rangedattackpower
nothing with rangeddamage

and

> [23:39] <MantisLord> actually wait a minute this might be SMSG_UPDATE_OBJECT for Player not creature :D
[23:40] <MantisLord> okay nvm actually. The only occurrences I see of UNIT_FIELD_MINRANGEDDAMAGE in my Full SSC ssniff
[23:40] <MantisLord> are updates to players
[23:40] <MantisLord> not creatures
[23:43] <Phatcat> I think you should make a comment about that on the PR so killerwife can see that.
[23:45] <MantisLord> ok 
[23:51] <MantisLord> talking to him now about it. I actually am looking in some other sniffs from TBC
[23:51] <MantisLord> and it seems like same thing
[23:51] <MantisLord> only occurs for player update

**Comment by Tobschinski** [comment]
Faction, I do not see a reason to keep both fields, faction_templates will always affect horde and alliance, friendly and hostile units. There is currently just one creature in classic_db with different values, some ghost in the Eastern Plaguelands that is summoned if you control the towers. That faction can be changed with scripts, and probably should be.

About the other stuff, I have never seen it to exist for creatures (except rangedbaseattacktime, which is always the same as meleebaseattacktime, I think). Just because it's part of SMSG_UPDATE_OBJECT for some units doesn't necessarily have to imply that it should be stored in creature_template. Especially if you can get it from somewhere else (loading baseattacktime twice, or set something as default value.

However, not partially removing these fields and wait for @cala to finally get all multipliers right (hurry the f*** up) to finish the classlevelstats_implementation makes sense. So maybe just focus on faction then ...

**Comment by cyberium** [comment]
For Faction i remember asking @Schmoozerd about it, if my memory is right i was stating something like.
Its for creature where faction depend on player faction at spawn. You have to read "FactionAlliance" as "Faction for Alliance player". Lot of change have been done in the core so iam not sure if its still right. And yes it can be done by script. So for that @Grz3s @killerwife @cala have to be ok.

**Comment by killerwife** [comment]
From my end if anyone wants to review all instances of using different ones in FA and FH columns and make them work by changing it in the script, be my guest.

**Pull request closed without merging**
