### PR TITLE
Add outstring_log function with empty args

### PR DESCRIPTION
**Pull request by 0x2aff**
Why there is no outstring_log() ?
Everyone loves less compiler errors :)

### CODE REVIEW

**Comment by Phatcat** [comment]
What? to get less compiler errors you fix the errors, you don't stop showing them...

**Comment by cyberium** [comment]
iam affread @Phatcat is right this resolve nothing

**Comment by Laizerox** [comment]
But compiler error is that we are passing empty string to a sprintf to create empty line. Which ia just a warning.

**Comment by Phatcat** [comment]
Alright, that makes a lot more sense. Do we really want a new function just to get rid of a few warnings, though?

**Pull request closed without merging**
