### PR TITLE
Update to OpenSSL 1.0.2k

### PR DESCRIPTION
**Pull request by some2**
Update from OpenSSL 1.0.2f to OpenSSL 1.0.2k

### CODE REVIEW

**Comment by cyberium** [comment]
Ok its always better to get latest code.
But why did you choose 1.0.2k? There is 1.1.x update already.
I know there is API change btw that may explain it.

**Comment by some2** [comment]
Yep, the API change and version 1.0.2 has LTS until 31-12-2019. (1.1.0 until 31-08-2018)

**Comment by cyberium** [comment]
Ok then its the best option. Thank for your contribution its realy appreciated.

**Comment by cyberium** [comment]
Thank you its merged.

**Pull request closed without merging**
