### PR TITLE
Fix crash at shutdown

### PR DESCRIPTION
**Pull request by Jose123456**
The boost::io_service created in NetworkThread is not being allowed to clean itself up in the destructor. Here's a quote from the boost docs:

> Alternatively, if the application requires that all operations and handlers be allowed to finish normally, the work object may be explicitly destroyed.

``` C++
boost::asio::io_service io_service;
auto_ptr<boost::asio::io_service::work> work(
    new boost::asio::io_service::work(io_service));
...
work.reset(); // Allow run() to exit. 
```

http://www.boost.org/doc/libs/1_62_0/doc/html/boost_asio/reference/io_service.html

### CODE REVIEW

**Comment by namreeb** [comment]
I don't see what your change is actually doing here, besides changing m_work into a pointer.  Surely the destructor is called in the implicit destructor of the parent without it being a separate heap allocation?

**Comment by Jose123456** [comment]
The order in which the destructors are called changes. Right now, the `work` destructor is called after the body of the `NetworkThread` destructor is called. The body invalidates objects that are still referenced in the `boost::io_service` operations queue, leading to crashes like this:

```
Core was generated by `./bin/mangosd -c etc/mangosd.conf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (LWP 20255)]
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000a562bb in Master::Run (this=0x5abfa6) at /mnt/misc/wowserver/mangos-classic/src/mangosd/Master.cpp:316
#2  0x0000000000a5c886 in boost::throw_exception<boost::system::system_error> (e=...) at /usr/include/boost/throw_exception.hpp:62
#3  0x000000000b337398 in ?? ()
#4  0x00007ffe4fe00970 in ?? ()
#5  0x0000000000a5adec in boost::asio::detail::socket_ops::accept (s=0, addr=0x200000000, addrlen=0x0, ec=...)
    at /usr/include/boost/asio/detail/impl/socket_ops.ipp:114
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

The stack is not corrupt, BTW. It's just that I ran gdb with a newer mangosd binary than the one that generated the core dump. I can try to build a version that matches if you want a better backtrace.

**Comment by Phatcat** [comment]
I actually just had this crash happen, (was running a core updated to [this commit](https://github.com/cmangos/mangos-classic/commit/62be39e2be0b05df82ec93a0bd53bee3a6443a8f), have updated now I see changes have been made to these functions just some hours ago)

````
`Exception code: C0000005 ACCESS_VIOLATION
Fault address:  005172B1 01:001162B1 C:\Mangos\mangos-classic\bin\Win32_Debug\mangosd.exe

Registers:
EAX:DDDDDDDD
EBX:18ABCE98
ECX:DDDDDDDD
EDX:19AEFD50
ESI:19AEFEA0
EDI:19AEFE3C
CS:EIP:0023:005172B1
SS:ESP:002B:19AEFD88  EBP:19AEFD8C
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010246

Call stack:
Address   Frame     Function      SourceFile
005172B1  00000000  WorldSocket::FinalizeSession+11  c:\mangos\mangos-classic\src\game\worldsocket.h line 131
00517289  00000000  WorldSession::Finalize+19  c:\mangos\mangos-classic\src\game\worldsession.h line 135
00643385  00000000  World::UpdateSessions+1E5  c:\mangos\mangos-classic\src\game\world.cpp line 1793
00642C43  00000000  World::Update+173  c:\mangos\mangos-classic\src\game\world.cpp line 1363
005B8829  00000000  WorldRunnable::run+89  c:\mangos\mangos-classic\src\mangosd\worldrunnable.cpp line 60
0060DDE1  00000000  MaNGOS::Thread::ThreadTask+21  c:\mangos\mangos-classic\src\shared\threading.cpp line 84
````

**Comment by Jose123456** [comment]
Yeah @namreeb's latest commits might address this as well. I'm testing it right now.

**Comment by Jose123456** [comment]
Nope. Still happens with latest master:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f22706e1740 (LWP 2252))]
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000a5a00b in boost::asio::detail::task_io_service_operation::destroy (this=0xb40ed38)
    at /usr/include/boost/asio/detail/task_io_service_operation.hpp:43
#2  0x0000000000a605d6 in boost::asio::detail::op_queue_access::destroy<boost::asio::detail::task_io_service_operation> (o=0xb40ed38)
    at /usr/include/boost/asio/detail/op_queue.hpp:47
#3  0x0000000000a5eb3c in boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>::~op_queue (this=0xb40ed60, 
    __in_chrg=<optimized out>) at /usr/include/boost/asio/detail/op_queue.hpp:81
#4  0x0000000000a6e03d in boost::asio::detail::task_io_service::~task_io_service (this=0xb40eca0, __in_chrg=<optimized out>)
    at /usr/include/boost/asio/detail/task_io_service.hpp:40
#5  0x0000000000a6e0aa in boost::asio::detail::task_io_service::~task_io_service (this=0xb40eca0, __in_chrg=<optimized out>)
    at /usr/include/boost/asio/detail/task_io_service.hpp:40
#6  0x0000000000a59d02 in boost::asio::detail::service_registry::destroy (service=0xb40eca0)
    at /usr/include/boost/asio/detail/impl/service_registry.ipp:101
#7  0x0000000000a59c16 in boost::asio::detail::service_registry::~service_registry (this=0xb40ec50, __in_chrg=<optimized out>)
    at /usr/include/boost/asio/detail/impl/service_registry.ipp:45
#8  0x0000000000a5cbbb in boost::asio::io_service::~io_service (this=0xb40eba0, __in_chrg=<optimized out>)
    at /usr/include/boost/asio/impl/io_service.ipp:53
#9  0x0000000000a64e8e in MaNGOS::NetworkThread<WorldSocket>::~NetworkThread (this=0xb40eba0, __in_chrg=<optimized out>)
    at /mnt/misc/wowserver/mangos-classic/src/shared/Network/NetworkThread.hpp:84
#10 0x0000000000a62dfa in std::default_delete<MaNGOS::NetworkThread<WorldSocket> >::operator() (this=0xb40eb50, __ptr=0xb40eba0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/unique_ptr.h:76
#11 0x0000000000a6124b in std::unique_ptr<MaNGOS::NetworkThread<WorldSocket>, std::default_delete<MaNGOS::NetworkThread<WorldSocket> > >::~unique_ptr
    (this=0xb40eb50, __in_chrg=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/unique_ptr.h:236
#12 0x0000000000a68a1c in std::_Destroy<std::unique_ptr<MaNGOS::NetworkThread<WorldSocket>, std::default_delete<MaNGOS::NetworkThread<WorldSocket> > > > (__pointer=0xb40eb50) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_construct.h:93
#13 0x0000000000a66f1e in std::_Destroy_aux<false>::__destroy<std::unique_ptr<MaNGOS::NetworkThread<WorldSocket>, std::default_delete<MaNGOS::NetworkThread<WorldSocket> > >*> (__first=0xb40eb50, __last=0xb40eb90) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_construct.h:103
#14 0x0000000000a646a1 in std::_Destroy<std::unique_ptr<MaNGOS::NetworkThread<WorldSocket>, std::default_delete<MaNGOS::NetworkThread<WorldSocket> > >*> (__first=0xb40eb50, __last=0xb40eb90) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_construct.h:126
#15 0x0000000000a62791 in std::_Destroy<std::unique_ptr<MaNGOS::NetworkThread<WorldSocket>, std::default_delete<MaNGOS::NetworkThread<WorldSocket> > >*, std::unique_ptr<MaNGOS::NetworkThread<WorldSocket>, std::default_delete<MaNGOS::NetworkThread<WorldSocket> > > > (__first=0xb40eb50, 
    __last=0xb40eb90) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_construct.h:151
#16 0x0000000000a60cc3 in std::vector<std::unique_ptr<MaNGOS::NetworkThread<WorldSocket>, std::default_delete<MaNGOS::NetworkThread<WorldSocket> > >, std::allocator<std::unique_ptr<MaNGOS::NetworkThread<WorldSocket>, std::default_delete<MaNGOS::NetworkThread<WorldSocket> > > > >::~vector (
    this=0x7ffd065d6cc8, __in_chrg=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_vector.h:424
#17 0x0000000000a5fc54 in MaNGOS::Listener<WorldSocket>::~Listener (this=0x7ffd065d6c90, __in_chrg=<optimized out>)
    at /mnt/misc/wowserver/mangos-classic/src/shared/Network/Listener.hpp:92
#18 0x0000000000a58175 in Master::Run (this=0x147f190) at /mnt/misc/wowserver/mangos-classic/src/mangosd/Master.cpp:232
#19 0x0000000000a50c73 in main (argc=1, argv=0x7ffd065d7038) at /mnt/misc/wowserver/mangos-classic/src/mangosd/Main.cpp:201
```

**Pull request closed without merging**
