### PR TITLE
[WIP] Pet Patch 1.2: No Rest For the Wicked

### PR DESCRIPTION
**Pull request by Phatcat**
Oh, @cala ... We're not done here yet ;D

Okay, evade function seems a bit tricky, nothing much here for you to test... yet.

---
This change is [Reviewable](https://reviewable.io/reviews/cmangos/mangos-classic/162)

### CODE REVIEW

**Comment by cala** [comment]
> Okay, evade function seems a bit tricky, nothing much here for you to test... yet.

Okay. My plate is quite full at the moment. Tell me when you need someone to test this and give feedback, please.

**Comment by Phatcat** [comment]
There we go, now there's a couple of things to test =) .. @cala :3

**Comment by cala** [comment]
Ok, I've schedule tomorrow evening for testing the few PRs I have on my list so I'll have a run for this one too.
Any specific things you'd like me to focus on/test about this PR?

**Comment by Phatcat** [comment]
Well, I'm going to list some of it;

This PR should fix stealth for pets breaking on melee (currently it can be tested on master with warlock succubuss invis)
It should make creatures summoned via EffectSummon also defend their owner
It should, well, maybe not completely fix pet evade, but it should hopefully improve on it.
It should make pets aggroable (which they are not currently, can be tested by taunting a pet that already has a victim)
It should fix an error message that is displayed currently when hunters load their pets from db (this is because the pet is loaded from db during the checkcast, but later in the checkcast, if it finds a petGUID it will fail, so we need to end the checkcast if we've loaded a pet from db.)

**Comment by cala** [comment]
Nice job! Everything went as described. So, that's ok for me.

The only remaining thing about pets, are for guardian pets from players: they are stuck on spawn if they have an EventAI but this is unrelated to this PR.

:+1:

**Comment by Phatcat** [comment]
@cala , I am looking at that right as we speak, and I think I found out why. I have a patch up for it, I build it on TBC... Don't ask me why... I'll port the commit onto this patch, expect it in maybe 10 - 15 minutes.

**Comment by Phatcat** [comment]
Also, pet evade is not completely done; pets who have a victim when their owners die will keep that victim till they themselves die - it has a ticket on our issue tracker somewhere, can't be arsed to find it right now; I am thinking if I should make the pet with a dead owner either delayed despawn (5 - 10 seconds), or have it go out of combat if its target is.... more than 30 yards away?

**Comment by Phatcat** [comment]
There are also some issues with the water elemental on TBC, as well as the warlock pet still behaving weird with neutral targets; also a few minor ones still open in my 'pet issues' ticket. Also quite a bit of guardians need to be scripted/ACID'd

All in all we're getting there.

**Comment by Phatcat** [comment]
@Tobschinski I remember you mentioned something about pets and owner death on pet patch 1, can you possibly help out here a bit with how pets actually behave when their owners die? What do they do if they have a victim, what if they don't have a victim? 
What player pets? do they despawn right away or slightly delayed?

**Comment by Phatcat** [comment]
Also, whoever told me that our mob AI was handling cases differently depending on mob class... No.. it does not... the AI is even more basic than the Pet AI. this is actually a joke to be honest; our generic AI is even more basic than basic. It's kind of embarrassing to be honest.

This is getting nuked. I'm nuking this.

**Comment by killerwife** [comment]
I pushed all up to pistachio on vengeance, and apparently pets cant be healed/bandaged now. Dunno if its specific to tbc branch.

**Comment by Phatcat** [comment]
@killerwife Now that just sounds strange.. I'll take a look at it in a bit, will also see if it's a thing exclusive to TBC, and then I'll try to solve it. Expect me on IRC in about an hour, Wifey =)

**Comment by dagochen** [comment]
Priest Mindcontrol -> servercrash

**Comment by Phatcat** [comment]
I'll look into that, thank you for noting.

**Comment by Tobschinski** [comment]
> @Tobschinski I remember you mentioned something about pets and owner death on pet patch 1, can you possibly help out here a bit with how pets actually behave when their owners die? What do they do if they have a victim? - how does one lose itself as a pets victim? (ie; when does creature pets actually start evading?)

I can try that ...

**Comment by Phatcat** [comment]
i excluded pet evade from this patch altogether as i was not sure on the correct behaviour. i would very much appreciate that.

**Comment by Phatcat** [comment]
@dagochen It looks like my work is not directly related to the crash. I'm not denying that it might be causing it, but it involves functions I don't quite understand nor are familiar with I'm afraid.

Crash dump: https://gist.github.com/Phatcat/5f40fff2ada4f74aea8619ef468f35f3

**Comment by dagochen** [comment]
Well before i pulled it did not crash ;)

**Comment by Phatcat** [comment]
https://github.com/cmangos/issues/issues/1002

when did you last pull?

**Comment by Phatcat** [comment]
Also note that i did intend to write 'noting', not 'nothing' - just noticed how rude my comment could come off to someone viewing it as a typo. It was not. Just getting that out there.

**Comment by dagochen** [comment]
5 min before i wrote your warlock pet thing crashes server ;)

**Comment by Phatcat** [comment]
Yeah, im gonna start needin crash reports from you

**Comment by Phatcat** [comment]
Also I meant when did you last pull BEFORE you were crashing on Mind Control?

**Comment by dagochen** [comment]
Oh that might be a little longer ago...1 week or 2?

**Comment by Phatcat** [comment]
This issue seems beyond my work; locally, i can mind control now no problem, but if i try to attack someone i just start running off and the server crashes. this one is really starting to bug me.

**Comment by cyberium** [comment]
@Phatcat let that mind control and eye of the beast problem for later. Iam on it but it requiere some change to be valided from wotlk and then backported.

**Comment by kuramajssken001** [comment]
I think it's related to the map.
Influence of terrain

**Pull request merged**
