### PR TITLE
Issue 1418 - One thread spins at 100% CPU

### PR DESCRIPTION
**Pull request by sterlingalexander**
With the addition of commit 1ccdd8e2, the console was by default enabled.  On Linux this caused one mangosd thread to spin at 100% CPU, polling the console constantly for input.  This commit resolved the issue by cleaning up the pre-processor defines and switching from usleep to nanosleep.  All of this is done using linux-specific code wrapped in pre-processor directives.

### CODE REVIEW

**Comment by cyberium** [comment]
First of all thank you very much for your contribution. It realy help to get real linux user feedback.

Could you please try to only replace ```linux``` by ```__linux__```.
Also after some though about it i think that code should be wrapped by ```__unix__``` instead because its supposed to work with ```__APPLE__``` too.
And why do you think replacing usleep by nanosleep help?

**Comment by sterlingalexander** [comment]
Ok, I can rework these to use __unix__ and see what happens.  

The rational for replacing usleep by nanosleep is two-fold:  usleep is considered 'obsolete' because it has inconsistent behavior when it is interrupted by a signal.  nanosleep can store and 'restart' the sleep, though I didn't take that approach here as it didn't seem warranted.  Also, nanosleep is an actual system call where usleep is a C(++) standard library construct that uses timers.  

In looking at the output, I have no real idea why the OSX builds failed, and the logs seem to point to files I didn't modify.  I don't have OSX hardware to test on unfortunately.  I do know of one openssl-headers issue, could this be the problem with OSX builds?

  https://spiegelmock.com/2016/07/05/mac-os-x-el-capitan-and-openssl-headers/

**Comment by cyberium** [comment]
The osx fail is not related to this don't worry at all about that.
My remark was more general.

Ok about nanosleep. Iam not so convainced about its use benefit though.
As an another alternative could you please try ```std::this_thread::sleep_for(std::chrono::microseconds(usec));```
It should be a portable way to do this. (chrono will be more heavly used in near future in cmangos)

**Comment by sterlingalexander** [comment]
Pushed some changes based on your feedback, let me know what you think.

**Comment by cyberium** [comment]
Please confirm me it work for you then its ready to merge :)

**Comment by sterlingalexander** [comment]
Tested on linux and it works.  No more 100% CPU and the console runs
commands as expected.

**Comment by cyberium** [comment]
Merged thanks

**Pull request closed without merging**
