### PR TITLE
Contrib: Adding script to detect overlapping spawns

### PR DESCRIPTION
**Pull request by Phatcat**
Another one by @Caydan

---
This change is [Reviewable](https://reviewable.io/reviews/cmangos/mangos-classic/181)

### CODE REVIEW

**Comment by dagochen** [comment]
Thx phatcat. Gave me some ideas for my script to generate all the poolings for the fishing-thing.

**Comment by cala** [comment]
I only had a quick look at the script but I'd be careful with this. There are places, mainly dungeons where the DB can have the same NPC spawned several times at the same place because it is part of a group of NPCs. Those NPCs are in a pool within a master pool to allow the game to pick a different group setup for each instance of the dungeon. 

From what I understand of the script (mobile phone screen and no PHP programming in a decade), such NPCs would be flagged as duplicate while they are not.

**Comment by killerwife** [comment]
Didn't I write SQL version of this actually?

**Comment by cala** [comment]
@killerwife you did and it was used by @tobschinski in https://github.com/classicdb/database/issues/841
Thanks.  :)

**Comment by killerwife** [comment]
@Phatcat I think that since it was possible to write it in SQL and PHP is much less accessible, I think we dont need this then.

**Comment by dagochen** [comment]
I just used this to create lots of inserts to pool the fishing holes on a server with an older database setup. Worked like a charm, 300 pool_entrys in 1 sec generated ;) But I didnt use the php version and ported it to java :P

**Comment by killerwife** [comment]
Well, I think a java version is certainly much easier to use.

**Comment by dagochen** [comment]
https://github.com/dagochen/MultiSpawnSQLGenerator

Quick and dirty, but working ;)

**Comment by Phatcat** [comment]
I am in no way attached to this, i just stumbled upon it and thought it might be useful.
 what do you mean php is not accessible? Its basically c programming. It doesnt get more accessible than that.

If you guys are saying java or sql over php for accessibility I might just cry.

Also it may be doing a check very much like one that you manually did but directly claiming that you made this is off honestly.

By the way this commit was made 5 days before you posted your sql overlap detection - if anything, it looks like -you- copied his method.

**Comment by killerwife** [comment]
For starters, I have yet to own a machine where PHP actually runs. Also java is present on any machine, and SQL is present on any mangos capable machine. Lastly, I never was a fan of writing PHP utility code, since for that you need php support, and thats not exactly windows domain.

And btw, I do not even know who he is.

**Comment by dagochen** [comment]
Java is not present on any machine. I know a lot of people who dont like it for security concerns and other personal reasons. Dont think this discussion leads to anything either :P

**Comment by Phatcat** [comment]
Dago actually already explained to me the reasoning for doing it in java or sql rather than php, even though I think the statement that it's more accessible is still faulty, it is indeed easier for Mangos devs considering we already got sql installed (also, who hasn't got java these days anyways)

You just made it sound like his work was inspired off of yours, which is kind of impossible. I lelieve you if you say you didn't make yours off of his. His work however seems slightly more developed (even though it's php)

**Comment by Phatcat** [comment]
Okay, so I guess a bunch of people have not got java.

**Comment by Phatcat** [comment]
Gonna close this due to dago having made his solution public.

**Pull request closed without merging**
